### ISSUE TITLE
Can't use this to turn the backlight OFF

### ISSUE THREAD

**Issue by wyatt8740** [FreeBSDDesktop/intel_backlight_fbsd#4]
In Linux, I use the original version of this tool in order to turn off my Thinkpad X201's backlight. However, the FreeBSD port appears to have an 'offset' of 0.5% applied, preventing the light from ever being turned off. I can only assume this is meant as some sort of safety feature, but I've been unable to find any other means of turning my backlight off. setting `min=0` and removing the `0.5 + ` on the mathematical operations fixes this. This also brings it closer to the functionality of the original FreeDesktop.org version of the tool.

[My fork](https://github.com/wyatt8740/intel_backlight_fbsd) has fixed this, but it's a sort of sloppy fix and it also allows the use of more precise numbers (with decimal places). I just don't feel comfortable making a pull request with it, because I didn't think of the program as a whole when I made my changes and just made them to get something working quickly. You can still look at [the commit](https://github.com/wyatt8740/intel_backlight_fbsd/commit/9da40e288d21fdb2c746cf7ce9e30f58b50a783a), if you want an idea of what I mean.

**Comment by johalun** [comment]
Thanks for the report. I don't know why this offset is there and I don't see any problem with removing it especially if it means same functionality as upstream. Would you like to clean up your patch and create a PR?

**Comment by wyatt8740** [comment]
Sure, I can do that. Finals week is coming up, though, so I might take a little while.

**Comment by wyatt8740** [comment]
Alright, request submitted. Turns out I did have five minutes to spare.

**Comment by wyatt8740** [comment]
Alright, this is now merged, so I guess I can close this.
