### ISSUE TITLE
intel_backlight reports negative values

### ISSUE THREAD

**Issue by driesmp** [FreeBSDDesktop/intel_backlight_fbsd#8]
Hi all!

I recently bought a new laptop the Lenovo T490 and I'm trying to configure brightness adjustments.
When I run the intel_backlight utility, it reports negative values for me.
Changing the value does change the brightness although any value results in a unreadable "black screen".
I'm running CURRENT on the machine in question.

/home/dries]$ intel_backlight
Current backlight value: -2147483648% (24242/0)

After some googling I found this forum post of a person that has the same issue: https://forums.freebsd.org/threads/freebsd-noob-fighting-brightness-touchpad-intel-driver.66347/
I think the most obvious reason is that my laptop is not supported (Whiskey Lake i5-825U), any chance to get support for this? :-).

**Comment by zeising** [comment]
Have you tried using acpi_video and fiddling with the hw.acpi.video.lcd0.brightness sysctl?

**Comment by driesmp** [comment]
When I try to "kldload acpi_video" my screen becomes black. Is the driver supposed to be loaded together with the drm i915kms port (graphics/drm-current-kmod)? However, when I load the driver it does seem to attach to something,I just get a black screen:
(from /var/log/messages) acpi_video0: <ACPI video extension> on vgapci0

EDIT: Never mind the loading issue, when loading both i915kms and acpi_video during boot (probably before the X11 server launches) it works fine. Although, the only brightness relevant value I find is the dev.acpi_ibm.0.lcd_brightness sysctl which doesn't adjusts the brightness of my screen.

**Comment by driesmp** [comment]
OK, I found the issue together with another FreeBSD developer that owns a T490. Apparently loading acpi_video before i915KMS doesn't expose brightness sysctl's. So this: "kld_list="acpi_video i915kms" doesn't work. I'll follow this up with a small addition to the manpage of acpi_video.
